# Generated by Django 3.1.2 on 2020-10-25 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outer_text', models.CharField(max_length=255)),
                ('inner_text', models.CharField(max_length=255)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True)),
                ('card_color', models.CharField(choices=[('WH', 'White'), ('BK', 'Black'), ('RD', 'Red'), ('OR', 'Orange'), ('YE', 'Yellow'), ('GR', 'Green'), ('BL', 'Blue'), ('IN', 'Indigo'), ('VI', 'Violet'), ('TE', 'Teal')], default='WH', max_length=2)),
                ('border_style', models.IntegerField(choices=[(0, 'Solid'), (1, 'Dashed'), (2, 'Dotted'), (3, 'Double')], default=0)),
                ('font_family', models.CharField(choices=[('SE', 'Serif'), ('SS', 'Sans-Serif')], default='SS', max_length=2)),
                ('font_style', models.CharField(choices=[('N', 'Normal'), ('I', 'Italics'), ('B', 'Bold'), ('U', 'Underline')], default='N', max_length=1)),
                ('text_align', models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('C', 'Center'), ('J', 'Justified')], default='L', max_length=1)),
                ('font_size', models.IntegerField(choices=[(0, 'Small'), (1, 'Medium'), (2, 'Large'), (3, 'Xtra Large')], default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorited_cards', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=255)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='instaky.card')),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorited_comments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
