# Generated by Django 3.1.2 on 2020-10-25 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instaky', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='favorited_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='favorited_by',
        ),
        migrations.AddField(
            model_name='card',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
