# Generated by Django 3.1.2 on 2020-10-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaky', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='font_size',
            field=models.CharField(choices=[(0, 'Small'), (1, 'Medium'), (2, 'Large'), (3, 'XXXtra Large')], default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='post',
            name='font_style',
            field=models.CharField(choices=[(0, 'Comic Sans'), (1, 'Papyrus'), (2, 'Wingdings')], default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_align',
            field=models.CharField(choices=[(0, 'Left'), (1, 'Right'), (2, 'Center'), (3, 'Justified')], default=0, max_length=1),
        ),
    ]
