# Generated by Django 3.1.2 on 2020-10-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaky', '0003_auto_20201022_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='font_style',
            field=models.CharField(choices=[('N', 'Normal'), ('I', 'Italics'), ('B', 'Bold'), ('U', 'Underline')], default='N', max_length=1),
        ),
    ]
